version: "3.9"

services:
  api-gateway:
    build: .
    container_name: api-gateway-lua
    ports:
      - "8080:8080"
    volumes:
      - ./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ./lua:/usr/local/openresty/nginx/lua:ro
      - ./conf:/usr/local/openresty/nginx/conf/conf:ro
      - ./logs:/usr/local/openresty/nginx/logs
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ISSUER=${JWT_ISSUER:-auth-service}
      - DB_HOST=${DB_HOST:-host.docker.internal}
      - DB_PORT=${DB_PORT:-5432}
      - DB_NAME=${DB_NAME:-gateway_db}
      - DB_USER=${DB_USER:-postgres}
      - DB_PASSWORD=${DB_PASSWORD:-postgres}
      - LOG_LEVEL=${LOG_LEVEL:-warn}
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 1024M
    networks:
      - microservices-net
      - rbac-gateway_rbac-network

  # ==================== whoami performance test ====================
  who-am-i:
    container_name: who-am-i
    image: traefik/whoami
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    ports:
      - "81:80"
    # deploy:
    #   resources:
    #     limits:
    #       cpus: "4.0"
    #       memory: 3072M
    networks:
      - microservices-net

  # ==================== PostgreSQL ====================
  # postgres:
  #   image: postgres:16-alpine
  #   container_name: rbac-postgres
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_DB: postgres
  #     POSTGRES_USER: ${DB_USERNAME:-postgres}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD:-12345}
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: [ "CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres}" ]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 5
  #   networks:
  #     - rbac-network

networks:
  microservices-net:
    # external: true   # Kết nối vào network chung của Spring Boot services
    name: microservices-net
    driver: bridge
  rbac-gateway_rbac-network:
    external: true
